Support MQTT and Domoticz authentications + Display connection state to Domoticz
t0mg/reacticz pull request #66
Opened 2017-02-08 14:12 UTC by davidlb

Support MQTT and Domoticz authentications, especially if you want to open services on the Internet.

**Note :** there is currently a bug in Domoticz, you need the next version (fixed with commit domoticz/domoticz@67c9863e1ffba1a9c7754ad0b52a9aa29f0b96da) or use a reverse proxy supporting CORS preflighted requests (nginx, apache, etc.)

I also added the connection status to Domoticz server as it was done for MQTT.

2017-02-08 14:44 UTC, t0mg commented
Oh wow awesome, thanks! I'll have a look at the changes tonight.

2017-02-08 18:55 UTC, davidlb commented
Fix in Domoticz is included in the last beta (version >= 3.6653)

2017-02-08 23:09 UTC, t0mg requested changes
Here are my comments, thanks a lot for doing this and sorry for being picky :)

By the way, I think we should edit AboutView to add the auth config to the serializer thing so that it doesn't get lost when sharing it (maybe just the logins at least but I don't see a huge security issue anyway). I can do that part in a subsequent change if you like.

2017-02-08 23:09 UTC, t0mg commented on src/util/JSONClientSingleton.js
> +    axios.head(this.serverUrl+ '/json.htm', axiosConfig).then(response => {
I'm getting  a compile error here because axiosConfig is undefined. I suppose you meant this.axiosConfig ?

2017-02-08 23:09 UTC, t0mg commented on src/SettingsView.js
> +          {mqttAuthRequired}
A small suggestion for readability: instead of the ternary assignment in mqttAuthRequired at line 73, you could put that layout in a function eg. renderMqttAuthForm() that returns the layout, and then here you could do :{this.state.mqttAuthChecked && this.renderMqttAuthForm()}
And the same with domoticz form. What do you think ? (I know I didn't to that for the welcome part at the top, but it used to be much shorter... maybe I should do that there too now)

2017-02-08 23:09 UTC, t0mg commented on src/SettingsView.js
> +            Authentication required:
I'd say "Use authentication", I think this wording is a little less confusing.

2017-02-08 23:09 UTC, t0mg commented on src/App.js
> +    this.mqtt.connect(config.mqttBrokerUrl, config.mqttLogin, config.mqttPassword);
This doesn't do anything unless you also modify the MqttClientSingleton. Maybe you forgot to add that bit to the pull request ?

2017-02-08 23:09 UTC, t0mg commented on src/util/JSONClientSingleton.js
> +    if (login  && password) {
extra white space

2017-02-08 23:09 UTC, t0mg commented on src/util/JSONClientSingleton.js
> +  setServerUrl(url, login, password) {
Please use opt_login, opt_password (a convention to indicate that they are optional).

2017-02-08 23:09 UTC, t0mg commented on src/util/JSONClientSingleton.js
> +            password: password
indent is wrong here (2 extra spaces). 
OK sorry for nitpicking, I'll stop now :)

2017-02-09 22:00 UTC, davidlb commented
Thanks for your feedback.
I should have fixed everything, it should be ok  :)

2017-02-10 00:16 UTC, t0mg commented
Awesome! Thanks for your work! I still want to rephrase the "Authentication required:" thing but I'll do it later :)

2017-02-10 00:16 UTC, merged