iOS manifest for iOS only
t0mg/reacticz pull request #99
Opened 2017-02-22 22:57 UTC by gerard33

Only load the iOS manifest on iOS devices.
Also automatic reload when manifest is changed.

2017-02-22 22:59 UTC, gerard33 commented
@t0mg I hope this works.
I added a javascript code to only load the ios.manifest on iOS devices.
Also some code from https://www.html5rocks.com/en/tutorials/appcache/beginner/ to automatically reload the page if the ios.manifest is changed.

Seems to work here with iOS and Chrome on Windows 7 (needed to clear to AppCache on Chrome to get rid of the ios.manifest).

Let me know if it works for you and what you think of it :)

2017-02-23 00:04 UTC, t0mg commented on public/index.html
> +</script>
Removing the <html> tag here makes the whole document invalid. Also, html element can only contain a head and a body tag.

Can you try this?
```
<!doctype html>
<html lang="en">
<head>
  all the meta tags...
  <script>
    if (navigator.userAgent.match(/(iPhone|iPod|iPad)/i)) {
      // BTW, this test is weak, eg IE Mobile also mentions iPhone in its user agent string...
      const htmlEl = document.getElementsByTagName('html')[0];
      htmlEl.setAttribute('manifest', '%PUBLIC_URL%/ios.manifest');

      // The rest of your manifest update detection code goes here, inside the user agent test.
      // ...
    }
  </script>
</head>
<body>
...
```

2017-02-23 12:18 UTC, t0mg requested changes
We need to keep index.html a valid html file. See my other comment for something we can try. If it doesn't work (ie fails at loading the manifest on iOS), and there is absolutely no other way for iOS to work, then I'd rather keep the manifest for everyone.

Thanks!

2017-02-23 22:06 UTC, gerard33 commented on public/index.html
> +</script>
Tried this and it works on iOS.

2017-02-23 22:22 UTC, t0mg reviewed
Thanks for the update! So does it still works on iOS this way?

2017-02-23 22:40 UTC, gerard33 commented
Yeah, if ios.manifest is changed this is noticed on iOS.

2017-02-23 23:51 UTC, merged